export const NavLinks =[
    {
        id:1,
        url:"#home",
        label:"Home",
    },
    {
        id:2,
        url:"#services",
        label:"Services",
    },
    {
        id:3,
        url:"#resume",
        label:"Resume",
    },
    {
        id:4,
        url:"#work",
       label:"Work",
    },
    {
        id:5,
        url:"#skill",
        label:"Skills",
    },
    {
        id:6,
        url:"#contact",
        label:"Contact",
    },
]